export const copy = {
  brand: "Noorzaa",
  tagline: "বাংলাদেশি নারীদের জন্য লাক্সারি ফ্যাশন",
  nav: {
    collections: "কালেকশন",
    about: "আমাদের গল্প",
    contact: "যোগাযোগ",
    track: "ট্র্যাক অর্ডার",
    myProduct: "আমার প্রোডাক্ট",
    myOrders: "আমার অর্ডার",
    cart: "কার্ট",
    account: "অ্যাকাউন্ট",
    login: "লগইন",
    logout: "লগআউট",
    admin: "অ্যাডমিন",
    notifications: "নোটিফিকেশন",
  },
  actions: {
    shopNow: "এখনই কিনুন",
    addToCart: "কার্টে যোগ করুন",
    addedToCart: "কার্টে যোগ হয়েছে",
    viewCart: "কার্ট দেখুন",
    checkout: "চেকআউট",
    placeOrder: "অর্ডার করুন",
    continueShopping: "আরও দেখুন",
    sendWhatsApp: "WhatsApp-এ পাঠান",
    save: "সংরক্ষণ করুন",
    delete: "মুছুন",
    edit: "এডিট",
    create: "নতুন যোগ করুন",
    apply: "প্রয়োগ করুন",
    upload: "ইমেজ আপলোড",
    print: "প্রিন্ট / PDF",
    close: "বন্ধ করুন",
  },
  cart: {
    title: "আপনার কার্ট",
    empty: "কার্টে এখন কিছু নেই।",
    summary: "অর্ডার সারাংশ",
    subtotal: "সাবটোটাল",
    discount: "ছাড়",
    shipping: "ডেলিভারি",
    total: "মোট",
    freeShipping: "নির্দিষ্ট অর্ডারে ফ্রি ডেলিভারি",
    coupon: "কুপন কোড",
    outOfStock: "স্টকে নেই",
  },
  checkout: {
    title: "অর্ডার সম্পন্ন করুন",
    successTitle: "অর্ডার গ্রহণ করা হয়েছে",
    successBody:
      "আপনার অর্ডার সফলভাবে রেকর্ড হয়েছে। আমাদের টিম শীঘ্রই WhatsApp বা ফোনে কনফার্মেশন পাঠাবে।",
  },
  search: {
    title: "প্রোডাক্ট খুঁজুন",
    placeholder: "নাম, ক্যাটাগরি বা ফ্যাব্রিক লিখুন...",
    noResults: "কোনো প্রোডাক্ট পাওয়া যায়নি।",
    filters: "ফিল্টার",
    allCategories: "সব ক্যাটাগরি",
    sortFeatured: "ফিচার্ড",
    sortPriceLow: "দাম: কম থেকে বেশি",
    sortPriceHigh: "দাম: বেশি থেকে কম",
  },
  account: {
    loginTitle: "স্বাগতম ফিরে",
    registerTitle: "Noorzaa সদস্য হোন",
    dashboardTitle: "আমার প্রোফাইল",
    ordersTitle: "অর্ডার করা আইটেম",
    noOrders: "এখনো কোনো অর্ডার নেই।",
    notificationsTitle: "নোটিফিকেশন",
    noNotifications: "কোনো নোটিফিকেশন নেই।",
    orderStatus: "অর্ডার স্ট্যাটাস",
    otpHint: "৬ সংখ্যার কোডটি Gmail ইনবক্স বা স্প্যাম ফোল্ডার থেকে লিখুন — লিখা শেষ হলেই অটো ভেরিফাই হবে।",
    saveProfile: "প্রোফাইল সেভ করুন",
    changePhoto: "প্রোফাইল ছবি",
  },
  admin: {
    title: "Noorzaa Admin",
    products: "প্রোডাক্ট",
    orders: "অর্ডার",
    categories: "ক্যাটাগরি",
    delivery: "ডেলিভারি ফি",
    coupons: "কুপন",
    offersProduct: "Offers Product",
    settings: "সেটিংস",
    analytics: "হিসাব",
    reports: "রিপোর্ট",
    loginTitle: "অ্যাডমিন লগইন",
    notifications: "নোটিফিকেশন",
  },
  reviews: {
    title: "রেটিং ও মতামত",
    placeholder: "আপনার অভিজ্ঞতা লিখুন...",
    submit: "মতামত দিন",
    noReviews: "এখনো কোনো মতামত নেই।",
  },
  offers: {
    banner: "চলমান অফার",
    popupTitle: "নতুন অফার ও প্রোডাক্ট",
  },
  form: {
    name: "পূর্ণ নাম",
    phone: "ফোন নম্বর",
    email: "ইমেইল (ঐচ্ছিক)",
    address: "ডেলিভারি ঠিকানা",
    district: "জেলা",
    note: "নোট (ঐচ্ছিক)",
    password: "পাসওয়ার্ড",
    payment: "পেমেন্ট পদ্ধতি",
    cod: "ক্যাশ অন ডেলিভারি",
    bkash: "bKash",
    nagad: "Nagad",
  },
  orderStatus: {
    pending: "অপেক্ষমাণ",
    confirmed: "নিশ্চিত",
    processing: "প্রসেসিং",
    out_for_delivery: "ডেলিভারিতে",
    delivered: "ডেলিভারি সম্পন্ন",
    cancelled: "বাতিল",
  },
} as const;
